package dev.ch8n.gittrends.data.model.local.list

import android.os.Parcelable
import androidx.room.Entity
import kotlinx.android.parcel.Parcelize


// https://youtrack.jetbrains.com/issue/KT-19300 this
// is a bug in IDE which tells to implement methods
// but its automatically generated by annotation processors
@Parcelize
data class TrendingItem(
    val avatar: String,
    val gitProfileName: String,
    val gitProfileUrl: String,
    val username: String,
    val projectDesc: String,
    val projectName: String,
    val projectUrl: String
) : Parcelable
